In [1]:
from pathlib import Path

import pandas as pd
import numpy as np

In [2]:
geoinfo_dir = Path('./2021')

In [3]:
artigos = pd.read_csv(
    geoinfo_dir / 'artigos.csv',
    quotechar='"',
    quoting=1,
    encoding='utf-8-sig'
)
print(f"Artigos: {len(artigos)} registros")

pessoas = pd.read_csv(
    geoinfo_dir / 'pessoas.csv',
    quotechar='"',
    quoting=1,
    encoding='utf-8-sig'
)
print(f"Pessoas: {len(pessoas)} registros")

autoria = pd.read_csv(
    geoinfo_dir / 'autoria.csv',
    quotechar='"',
    quoting=1,
    encoding='utf-8-sig'
)
print(f"Autoria: {len(autoria)} registros")

comite = pd.read_csv(
    geoinfo_dir / 'comite_cientifico.csv',
    quotechar='"',
    quoting=1,
    encoding='utf-8-sig'
)
print(f"Comitê: {len(comite)} registros")

organizacao = pd.read_csv(
    geoinfo_dir / 'organizacao.csv',
    quotechar='"',
    quoting=1,
    encoding='utf-8-sig'
)
print(f"Organização: {len(organizacao)} registros")

evento = pd.read_csv(
    geoinfo_dir / 'evento.csv',
    quotechar='"',
    quoting=1,
    encoding='utf-8-sig'
)
print(f"Evento: {len(evento)} registros")

Artigos: 29 registros
Pessoas: 168 registros
Autoria: 121 registros
Comitê: 61 registros
Organização: 2 registros
Evento: 1 registros

In [4]:
artigos.head()

,id_artigo,titulo,abstract,n_paginas,tipo_artigo,lingua,n_edicao
0,1,Monitoring the spatiotemporal dynamics of surf...,Water stored in dams and reservoirs is essenti...,15,full,english,22
1,2,Towards an analytical and operational trajecto...,"In recent years, many research works involving...",12,full,english,22
2,3,Mapping irrigated rice using MSI/Sentinel-2 ti...,The State of Rio Grande do Sul is the largest ...,9,full,english,22
3,4,Study on changing trends in climatic extremes ...,It is noticeable that the climate trends are c...,12,full,english,22
4,5,Effects of landscape fragmentation in the Prot...,Tropical forest remnants play an important rol...,11,full,english,22

In [5]:
pessoas.head()

,id_pessoa,nome,instituicao
0,1,Bello Abubakar Abubakar,Nigerian Defence Academy
1,2,Sani Abubakar Abubakar,Kaduna Polytechnic
2,3,Damião Ribeiro de Almeida,Universidade Federal de Campina Grande (UFCG)
3,4,Aillkeen Bezerra de Oliveira,Universidade Federal de Campina Grande (UFCG)
4,5,Samuel Pereira de Vasconcelos,Universidade Federal de Campina Grande (UFCG)

In [6]:
autoria.head()

   id_autoria  id_artigo  id_pessoa  ordem_autoria  autor_correspondente
0           1          1        1.0              1                 False
1           2          1        2.0              2                 False
2           3          2        3.0              1                 False
3           4          2        4.0              2                 False
4           5          2        5.0              3                 False

In [7]:
comite.head()

   id_revisor  id_pessoa  n_edicao
0           1        111        22
1           2        110        22
2           3        112        22
3           4        113        22
4           5        114        22

In [8]:
organizacao.head()

   id_organizador  id_pessoa         funcao  n_edicao
0               1        111  Program Chair        22
1               2        110  General Chair        22

In [9]:
evento.head()

   id_evento  n_edicao   ano                local
0          1        22  2021  São José dos Campos

In [10]:
#DF Papers
df = artigos.merge(autoria, on='id_artigo')
df = df.merge(pessoas[['id_pessoa', 'nome', 'instituicao']], on='id_pessoa')

df_papers = df.groupby('id_artigo').agg({
    'titulo': 'first',
    'abstract': 'first',
    'tipo_artigo': 'first',
    'lingua': 'first',
    'n_edicao': 'first',
    'nome': list,
    'instituicao': list
}).reset_index()
df_papers

,id_artigo,titulo,abstract,tipo_artigo,lingua,n_edicao,nome,instituicao
0,1,Monitoring the spatiotemporal dynamics of surf...,Water stored in dams and reservoirs is essenti...,full,english,22,"[Bello Abubakar Abubakar, Sani Abubakar Abubakar]","[Nigerian Defence Academy, Kaduna Polytechnic]"
1,2,Towards an analytical and operational trajecto...,"In recent years, many research works involving...",full,english,22,"[Damião Ribeiro de Almeida, Aillkeen Bezerra d...",[Universidade Federal de Campina Grande (UFCG)...
2,3,Mapping irrigated rice using MSI/Sentinel-2 ti...,The State of Rio Grande do Sul is the largest ...,full,english,22,"[Juliana de Abreu Araújo, Allan Henrique Lima ...",[Instituto Nacional de Pesquisas Espaciais (IN...
3,4,Study on changing trends in climatic extremes ...,It is noticeable that the climate trends are c...,full,english,22,"[Filipe Junio S. Coelho, Marconi de Arruda Per...",[Universidade Federal de São João Del Rei (UFS...
4,5,Effects of landscape fragmentation in the Prot...,Tropical forest remnants play an important rol...,full,english,22,"[Igor José Malfetoni Ferreira, Debora Cristina...",[Instituto Nacional de Pesquisas Espaciais (IN...
5,6,TopoGeo: a data model for elaboration of cadas...,The deed description and the survey plan prope...,full,english,22,"[Leandro L. S. França, Julierne Pinheiro, Joel...","[Universidade Federal de Pernambuco (UFPE), Mi..."
6,7,Anomaly detection based method for spatio-temp...,Remote Sensing technologies and Machine Learni...,full,english,22,"[Vinícius L. S. Gino, Rogério G. Negri, Felipe...","[Universidade Estadual Paulista (UNESP), Unive..."
7,8,Spatial data handling in NoSQL databases: a us...,Spatial data handling is a core aspect in seve...,full,english,22,"[Heron Carlos Gonçalves, Anderson Chaves Carniel]",[Universidade Tecnológica Federal do Paraná (U...
8,9,SAFmaps: the WebGIS for sustainability assessm...,"This paper presents the SAFmaps, an open-acces...",full,english,22,"[Marjorie M. Guarenghi, João Luís Santos, Arna...","[Universidade Estadual de Campinas (UNICAMP), ..."
9,10,A framework for the generation of the rainwate...,Urbanization in Brazilian cities often occurs ...,full,english,22,"[Pedro Vitor Duarte Guimarães, Marconi de Arru...",[Universidade Federal de São João Del Rei (UFS...
10,11,Classification of the water volume of dams usi...,Deep Convolutional Neural Networks (DCNN) have...,full,english,22,"[Mateus de Souza Miranda, Renato de Sousa Maxi...",[Instituto Nacional de Pesquisas Espaciais (IN...
11,12,Shalstab and TRIGRS: comparison of two models ...,Landslides are natural phenomena occurring wor...,full,english,22,"[Téhrrie Caroline Konig Ferraz Pacheco, Herman...",[Instituto Nacional de Pesquisas Espaciais (IN...
12,13,Detection of spikes in single-beam bathymetry ...,The process of detecting spurious depth (spike...,full,english,22,"[Karine Pinheiro, Gabriela Gouveia Lana, Laura...","[Universidade Federal de Viçosa (UFV), Univers..."
13,14,Lightning-induced wildfire in Serra do Cipó Na...,Analysis was performed to search all CG lightn...,full,english,22,"[Vanúcia Schumacher, Marco Aurélio Barros]",[Instituto Nacional de Pesquisas Espaciais (IN...
14,15,Evaluating a self-organizing map approach to c...,Brazil has a substantial diversity of agricult...,full,english,22,"[Marcos A. S. da Silva, Leonardo N. Matos, Flá...","[Embrapa Tabuleiros Costeiros, Universidade Fe..."
15,16,Characterization of center pivot irrigation sy...,This study purposes identify the changes in ce...,full,english,22,"[Philipe Souza Siműes, Marionei Fomaca de Sous...",[Instituto Nacional de Pesquisas Espaciais (IN...
16,17,Description of land cover and susceptibility t...,"The environmental issues, like burn events and...",full,english,22,"[Felipe N. Souza, Rogério G. Negri, Vinícius L...","[Universidade Estadual Paulista (UNESP), Unive..."
17,18,A method for generating and sharing 3D sanitat...,The three-dimensional representation of realit...,full,english,22,"[Kauê de Moraes Vestena, Nathan Damas Antonio,...","[Universidade Federal do Paraná (UFPR), Univer..."
18,19,Estrutura urbana na Amazônia paraense a partir...,At the interface between concept and measureme...,short,portuguese,22,"[Julia Corrêa Côrtes, José Diego Gobbo Alves, ...","[Universidade Estadual de Campinas (UNICAMP), ..."
19,20,'Do Pasto ao Prato': a citizen science initiat...,Livestock farming in Brazil is linked to negat...,short,english,22,"[Erasmus zu Ermgassen, Vivian Ribeiro, Patrick...","[UCLouvain, Stockholm Environment Institute, U..."
20,21,Comparaçăo da componente vertical GNSS determi...,The improvement of the Global Navigation Satel...,short,portuguese,22,"[Samoel Giehl, Regiane Dalazoana, Túlio Alves ...","[Universidade Federal do Paraná (UFPR), Univer..."
21,22,Análise da concordância entre dados de degrada...,The characterization of forest degradation is ...,short,portuguese,22,"[Aline Daniele Jacon, Maria Isabel Sobral Esca...",[Instituto Nacional de Pesquisas Espaciais (IN...
22,23,IBGE Statistical Grid in Compact Representation,This article describes the development of the ...,short,english,22,"[Peter Krauss, Luis Felipe Bortolatto da Cunha...",[Instituto de Tecnologias Geo-Sociais AddressF...
23,24,Automated cloud coverage analysis with Brazil ...,This paper approaches the topic of Data Cubes ...,short,english,22,"[Thainara Munhoz Alexandre de Lima, Romulo Mar...",[Instituto Nacional de Pesquisas Espaciais (IN...
24,25,Análise das condiçőes ambientais na Serra do C...,"This work analyzed data of precipitation, days...",short,portuguese,22,"[Gilberto Ribeiro de Queiroz, Guilherme Martin...",[Instituto Nacional de Pesquisas Espaciais (IN...
25,26,Utilizando o padrão SpatioTemporal Asset Catal...,The Brazil Data Cube project (BDC) is an initi...,short,portuguese,22,"[Mateus de Souza Macul, Paulo W. Pinto da Cunh...",[Instituto Nacional de Pesquisas Espaciais (IN...
26,27,Gerenciamento de dados geográficos no Projeto ...,The Brumadinho UFMG Platform was designed for ...,short,portuguese,22,"[Bruno dos Santos, Gilberto Eidi Teramoto Oliv...",[Instituto Nacional de Pesquisas Espaciais (IN...
27,28,Occurrence of marine heatwaves along the north...,Marine Heatwaves (MHWs) are defined as high-im...,short,english,22,"[Ingrid L. Santana, Michele Brito Pinheiro]","[Universidade Federal de Minas Gerais (UFMG), ..."
28,29,A meta-classifier approach for outlier identif...,Geodetic networks provide the positional basis...,short,english,22,"[Luci A. Nicolau, Gabriel Lucas Xavier da Silv...","[Universidade Federal de Minas Gerais (UFMG), ..."

In [11]:
#DF Comitê
df_comite = comite.merge(pessoas, on='id_pessoa')
df_comite = df_comite[['id_pessoa', 'nome', 'instituicao', 'n_edicao']]
df_comite = df_comite.sort_values('nome').reset_index(drop=True)
df_comite

,id_pessoa,nome,instituicao,n_edicao
0,116,A. Miguel Monteiro,INPE,22
1,111,Alan J. Salomão Graça,Universidade Estadual do Rio de Janeiro (UERJ),22
2,112,Alber Sànchez,INPE,22
3,113,Alessandra Palmeiro,UFRJ,22
4,114,Ana Clara Moura,UFMG,22
...,...,...,...,...
56,164,Sonaira Silva,UFAC,22
57,166,Tatiana Kuplich,INPE,22
58,165,Thales Köorting,INPE,22
59,167,Tiago Carneiro,UFOP,22
60,168,Vivian Fernandes,UFBA,22